### ISSUE TITLE
RKI Daten geschrottet

### ISSUE THREAD

**Issue by EmTee70** [swildermann/COVID-19#16]
Hallo, durch den Fehler beim RKI heute Nacht und die Korrektur stehen jetzt negative Werte für heute in:

https://covid19publicdata.blob.core.windows.net/rki/covid19-germany-federalstates.csv

Viellleicht löst es sich ja von alleine...

**Comment by swildermann** [comment]
Ist bei Korrekturen natürlich der Logik geschuldet, da wir beim Beladen die Differenz berechnen.
