### ISSUE TITLE
covid19-germany-federalstates.csv broke

### ISSUE THREAD

**Issue by bjornpiltz** [swildermann/COVID-19#19]
Hi, 
[covid19-germany-federalstates.csv](https://covid19publicdata.blob.core.windows.net/rki/covid19-germany-federalstates.csv) just got corrupted. For instance in the row for Thüringen you have the same numbers for "infections,deaths" as "newinfections,newdeaths".

```csv
id,Country/Region,federalstate,infections,deaths,date,newinfections,newdeaths
...
4858,Germany,Thuringia,39647,907,2020-12-29,39647,907
```

Thanks for your excellent service!

**Comment by TKlerx** [comment]
Thank you @bjornpiltz for the issue.
We will have a look at it.

**Comment by TKlerx** [comment]
We had some issues with the functions and are currently looking into how to get in the correct data for the end of December up to now.
For today (and hopefully the future) everything should be fine again.

**Comment by bjornpiltz** [comment]
Thanks! Looks great.
