### ISSUE TITLE
Data - Dates missing

### ISSUE THREAD

**Issue by EmTee70** [swildermann/COVID-19#20]
In the file  https://covid19publicdata.blob.core.windows.net/rki/covid19-germany-federalstates.csv - witch is a great service from you - the data form 2020-12-27 and  2020-12-28 is missing, would be cool if you could get them inserted.

**Comment by TKlerx** [comment]
Thank you @EmTee70 for the issue.
We will have a look at it.

**Comment by EmTee70** [comment]
Hint? Today no update at all was performed - so last data from yesterday.

**Comment by TKlerx** [comment]
Sorry, I did not find the time until now to look at it.
Somehow, the data gathering just did not run. But it did not show a failure, either.

So the data for those dates is somewhat "lost" which means we have to gather it manually to have complete data.
For the upcoming days I am still looking into this.

**Comment by EmTee70** [comment]
Thank you! For the missing two days for my use case it would be good enough to copy the totals of the day(s) before.
So that the number would look the same as if no new numbers where reported in this two days.
Could I express myself well enough?

**Comment by TKlerx** [comment]
So the functions are running again, but we need to get the data for the past/missing days.
I don't have more time now, but will hopefully fill the missing data in the evening with the correct data (not just fill up with the previous days).

**Comment by EmTee70** [comment]
Thank you a lot!, Vielen Dank!
