### ISSUE TITLE
covid19-germany-federalstates.csv no update sinze 2021-01-06

### ISSUE THREAD

**Issue by EmTee70** [swildermann/COVID-19#22]
Please take a look! 
Best regards mt.

**Comment by swildermann** [comment]
Thats right, taking a look at it atm.

**Comment by swildermann** [comment]
Also: If you need this data for a business critical application, feel free to clone the source code at let it run in your own environment. We are maintaining this as good as we can besides our main jobs.

**Comment by EmTee70** [comment]
Vielen Dank für Ihre Mühe, Thank you!
